[package]
name = "poetry-udeps"
version = "0.1.0"
edition = "2021"
authors = ["Luke Hsiao <luke@hsiao.dev>"]
description = "find unused dependencies in pyproject.toml"
repository = "https://github.com/lukehsiao/poetry-udeps"
homepage = "https://github.com/lukehsiao/poetry-udeps"
license = "MIT OR Apache-2.0"
keywords = ["poetry", "dependencies"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["wrap_help", "derive", "suggestions"] }
clap-verbosity-flag = "2.0.0"
crossbeam-channel = "0.5.6"
ignore = "0.4.19"
log = "0.4.17"
nom = "7.1.2"
toml = "0.5.10"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt"] }
xshell = "0.2.3"
